[package]
name = "room"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dev-dependencies]
serde_urlencoded = ''

[dependencies]
derive-newtype = ''
smart-default = ''
derive_more = ''
anyhow = ''
fehler = ''
serde = ''
ron = ''
chrono = ''
#geo = { version = '', features = ['use-serde'] }
geocoding = ''
persistentcache = { path = '../persistentcache' }
#persistentcache = { git = 'https://github.com/stefan-k/persistentcache-rs' }
#framework = { path = '../framework' }
itertools = ''
dirs = ''
serde_json = ''
lazy_static = ''
reqwest = ''
url = ''
map = { path = 'map' }
bytes = { version = '', features = ['serde'] }
kuchiki = ''
nom = ''
