[package]
name = "map"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
noisy_float = { version = '', features = ['serde-1'] } # why -1?
fehler = ''
anyhow = ''
serde = ''
geo-types = { version = '', features = ['serde'] }
geocoding = ''
persistentcache = { path = '../../persistentcache' }
#persistentcache = { git = 'https://github.com/stefan-k/persistentcache-rs' }
itertools = ''
dirs = ''
reqwest = ''
#static-http-cache = ''
#static-http-cache = { git = 'https://gitlab.com/Screwtapello/static_http_cache' }
static-http-cache = { path = '../../static_http_cache' }
serde_json = ''
lazy_static = ''
cfg-if = ''
bytes = ''
